language: go

go:
  - 1.14.x
  
os:
  - linux
  - osx

before_install:
  - go get github.com/mattn/goveralls

sudo: false

script:
  - go vet -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci